

services:
  postgres:
    image: postgres:15
    container_name: postgres-ai_interviews
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai_interviews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_interviews_net

  backend:
    build:
      context: ./backend
    container_name: backend-ai_interviews
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - ai_interviews_net
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    container_name: frontend-ai_interviews
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - ai_interviews_net
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  postgres_data:

networks:
  ai_interviews_net:
